### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by HibernantBear**
Add method to solve terminate while extension not set up or stuck during extension setting up(especially can't connect to npm server)

### CODE REVIEW

**Comment by anseki** [comment]
Hi @HibernantBear, thank you for the PR.

You should not abort the installing any extension because it may break something. And also, if the installing was unfortunately aborted, you should re-install the extension. We can't support `npm install` because it might already be broken.

**Comment by HibernantBear** [comment]
but still if I reinstall under bad connection this will never get through, so I think sometimes a manual method(it does work) still need cause this extension need other stuff that have to be download and configure by npm. man, this is a  awesome extension to do with color edit but if I live in China such a magic place and try get this extension to be set up by VS Code's npm, it gonna not wrok(sad face).

**Comment by anseki** [comment]
I see.
That contains two cases:

- When the installing was aborted, you should re-install the extension. `npm install` is not supported and VS Code doesn't support recovering aborted installing.
- When NPM installing doesn't work such as China, the information is required for them.

I will adjust your PR and merge it for second one.

**Comment by anseki** [comment]
I merged it manually.
Thank you for the PR 😄

**Comment by HibernantBear** [comment]
thank you very much, hope this will be helpful. Hope your extension become more and more better, and thanks for your hard working to provide us such a good tool(It is do so good when I use this to tweak color, no more need of Dreamweaver ^_^).

**Comment by anseki** [comment]
Thank you! 😄

**Pull request closed without merging**
